### ISSUE TITLE
enable javascript and cookies to continue

### ISSUE THREAD

**Issue by sesamehowie** [WhereIsMyMindDL/Base_Onchain_Summer#1]
несколько дней назад начало на минтах давать ошибку 403, решил глянуть что есть в паблике, попробовал хедеры как у тебя, принцип работы тот же. дает ли тебе ту же ошибку? спасибо за ответ

**Comment by WhereIsMyMindDL** [comment]
да брат, я хз в чем проблема, поставил рандом юа на каждый запрос, теперь иногда прокает

**Comment by sesamehowie** [comment]
в общем, там они поцепили bugsnag, есть вариант дергать куки через селен или плейврайт. но лично я решил все на уровне контракта делать, там все равно большинство минтов используют один интерфейс. спасибо
